/**
 * ⚠️  AUTO-GENERATED by backend/export_fallback.py — DO NOT EDIT BY HAND.
 *
 * Generated: 2026-07-31 23:03:22 UTC
 * Source DB:  sqlite:///dev.db
 *
 * This file is the SINGLE SOURCE OF TRUTH for the deployed (static) site.
 * Workflow:
 *   1. Edit content via the local dashboard (local backend + local DB).
 *   2. Re-run `DATABASE_URL=... python backend/export_fallback.py`.
 *   3. Commit this file and redeploy the frontend (Vercel).
 *
 * Regenerate after any dashboard edit so the static site stays in sync.
 */

import type { PortfolioData } from "@/lib/api";

export const fallbackProfile = {
  "id": 1,
  "name": "Saifullah Khan",
  "title": "Software Engineer | Full Stack Developer",
  "role": "Software Engineer | Full Stack Developer",
  "description": "Full Stack Developer with professional experience building web applications, REST APIs, and data-driven systems using Python, .NET, JavaScript and React. Experienced in backend development with Flask, FastAPI, Django, ASP.NET and microservice-based architectures — API design, authentication and authorization (JWT, RBAC), database design, and integrating frontend applications with backend services across MySQL, PostgreSQL, MongoDB, Elasticsearch, Neo4j and Kafka.",
  "summary": "Full Stack Developer with professional experience building web applications, REST APIs, and data-driven systems using Python, .NET, JavaScript and React. Experienced in backend development with Flask, FastAPI, Django, ASP.NET and microservice-based architectures — API design, authentication and authorization (JWT, RBAC), database design, and integrating frontend applications with backend services across MySQL, PostgreSQL, MongoDB, Elasticsearch, Neo4j and Kafka.",
  "email": "saifullahkhank66@gmail.com",
  "phone": "03007117755",
  "location": "Lahore, Pakistan",
  "linkedin": "https://linkedin.com/in/saifullah-khan",
  "github": "https://github.com/saifullahkhancs",
  "profile_image_url": "/images/portrait.jpeg",
  "hero_banner_url": "/images/hero-banner.png",
  "resume_url": "/images/resume.pdf"
};

export const fallbackExperiences = [
  {
    "id": 1,
    "role": "Software Engineer",
    "company": "Technogenics",
    "location": "Lahore, Pakistan",
    "period": "Aug 2024 – Jan 2026",
    "points": [
      "Developed and maintained Python backend services and RESTful APIs using Flask and FastAPI within a microservice-based architecture.",
      "Maintained a CMS built on Django REST Framework and React, backed by MongoDB and Neo4j, managing data spanning millions of URLs, IPs and domains plus thousands of ransomware, malware and threat-actor records.",
      "Built REST APIs, GraphQL endpoints and Kafka consumer pipelines for automated ingestion across 4 databases (MySQL, MongoDB, Elasticsearch, Neo4j).",
      "Developed and customized Scrapy crawlers running weekly to collect and process PSIRT advisory data for the intel system.",
      "Worked with Docker-based development environments for building, running and debugging backend services."
    ],
    "sort_order": 0
  },
  {
    "id": 2,
    "role": "Associate Software Engineer",
    "company": "DSME Global Links",
    "location": "Lahore, Pakistan",
    "period": "Oct 2023 – Aug 2024",
    "points": [
      "Developed and maintained backend web and mobile applications using ASP.NET, C# and MySQL.",
      "Contributed to workflow-driven features including scheduling, reporting, booking and user management modules.",
      "Performed API testing and validation using Postman and custom Python scripts.",
      "Collaborated directly with clients to translate business needs into technical solutions."
    ],
    "sort_order": 1
  },
  {
    "id": 3,
    "role": "Research Engineer",
    "company": "Valyrian System Incorporation",
    "location": "Remote",
    "period": "Aug 2022 – Aug 2023",
    "points": [
      "Conducted research on high-performance packet processing using XDP and DPDK in Linux environments.",
      "Evaluated network performance and throughput using iperf, TRex and mpstat.",
      "Participated in experiments demonstrating packet filtering and rerouting at multi-million packet throughput.",
      "Studied Linux networking internals and system performance optimization techniques."
    ],
    "sort_order": 2
  }
];

export const fallbackProjects = [
  {
    "id": 1,
    "name": "LinkeFlow",
    "tagline": "LinkedIn Automation Platform",
    "period": "May 2026 – Present",
    "description": "Backend automation platform that schedules and executes LinkedIn actions with human-mimicking browser behavior and per-account rate limiting. JWT auth with RBAC, AES-256-GCM credential encryption and a Redis-backed daily action limiter. Deployed on an Azure VM with Nginx and systemd.",
    "stack": [
      "FastAPI",
      "Celery",
      "Redis",
      "PostgreSQL",
      "Playwright",
      "Azure"
    ],
    "project_url": "",
    "projectUrl": "",
    "video_url": "",
    "videoUrl": "",
    "featured": true,
    "sort_order": 0
  },
  {
    "id": 2,
    "name": "Job Easy",
    "tagline": "Job Application Automation Platform",
    "period": "Personal Project",
    "description": "Job-application automation platform with a FastAPI backend and React/Vite frontend. SQLAlchemy and Alembic for data modeling and migrations, JWT-based auth and a role-based approval workflow (visitor → customer → admin) gating email-sending features with encrypted credential storage.",
    "stack": [
      "FastAPI",
      "React",
      "SQLAlchemy",
      "Alembic",
      "JWT"
    ],
    "project_url": "",
    "projectUrl": "",
    "video_url": "",
    "videoUrl": "",
    "featured": true,
    "sort_order": 1
  },
  {
    "id": 3,
    "name": "Strike Ready",
    "tagline": "Cybersecurity Intelligence Platform",
    "period": "Technogenics",
    "description": "Contributed to backend services and data ingestion workflows. Managed ingestion from crawler systems, multiple databases and research sources into Elasticsearch and Neo4j, maintaining pipelines across several microservices.",
    "stack": [
      "Python",
      "Elasticsearch",
      "Neo4j",
      "Kafka",
      "Scrapy"
    ],
    "project_url": "",
    "projectUrl": "",
    "video_url": "",
    "videoUrl": "",
    "featured": false,
    "sort_order": 2
  },
  {
    "id": 4,
    "name": "OOMS",
    "tagline": "Online Order Management System",
    "period": "Mar 2026 – Apr 2026",
    "description": "Scalable architecture for an online food ordering system using .NET 10 and Clean Architecture, with authentication, authorization and role-based access control for user permissions.",
    "stack": [
      ".NET 10",
      "Clean Architecture",
      "RBAC"
    ],
    "project_url": "",
    "projectUrl": "",
    "video_url": "",
    "videoUrl": "",
    "featured": false,
    "sort_order": 3
  },
  {
    "id": 5,
    "name": "Social Media Platform",
    "tagline": "Twitter Clone",
    "period": "Personal Project",
    "description": "Twitter-like web application with user authentication, tweets, likes, sharing and follow functionality, plus clean UI layouts and lightweight animations.",
    "stack": [
      "Flask",
      "JavaScript",
      "MySQL"
    ],
    "project_url": "",
    "projectUrl": "",
    "video_url": "",
    "videoUrl": "",
    "featured": false,
    "sort_order": 4
  }
];

export const fallbackSkills = [
  {
    "id": 1,
    "group": "Programming Languages",
    "group_name": "Programming Languages",
    "items": [
      "Python",
      "C#",
      "JavaScript"
    ],
    "sort_order": 0
  },
  {
    "id": 2,
    "group": "Backend Frameworks",
    "group_name": "Backend Frameworks",
    "items": [
      "Flask",
      "FastAPI",
      "Django",
      "Django REST Framework",
      "Scrapy",
      "ASP.NET Core"
    ],
    "sort_order": 1
  },
  {
    "id": 3,
    "group": "Databases",
    "group_name": "Databases",
    "items": [
      "MySQL",
      "PostgreSQL",
      "MongoDB",
      "Elasticsearch",
      "Neo4j",
      "Redis"
    ],
    "sort_order": 2
  },
  {
    "id": 4,
    "group": "Messaging & Realtime",
    "group_name": "Messaging & Realtime",
    "items": [
      "Kafka"
    ],
    "sort_order": 3
  },
  {
    "id": 5,
    "group": "Frontend",
    "group_name": "Frontend",
    "items": [
      "React",
      "HTML/CSS"
    ],
    "sort_order": 4
  },
  {
    "id": 6,
    "group": "Architecture",
    "group_name": "Architecture",
    "items": [
      "Microservices",
      "Clean Architecture",
      "MVC",
      "MVT"
    ],
    "sort_order": 5
  },
  {
    "id": 7,
    "group": "Auth & Security",
    "group_name": "Auth & Security",
    "items": [
      "JWT",
      "Role-Based Access Control",
      "API Security",
      "Rate Limiting"
    ],
    "sort_order": 6
  },
  {
    "id": 8,
    "group": "Familiar With",
    "group_name": "Familiar With",
    "items": [
      "Docker",
      "Kubernetes",
      "Azure",
      "Playwright",
      "Celery"
    ],
    "sort_order": 7
  }
];

export const fallbackEducations = [
  {
    "id": 1,
    "school": "Namal University, Mianwali",
    "degree": "Bachelor of Computer Science",
    "period": "Jul 2019 – Jul 2023",
    "cgpa": "3.42 / 4.0",
    "coursework": "Artificial Intelligence, Machine Learning, Database Management, Software Engineering, Computer Networks, Operating Systems, Data Analysis, Human Computer Interaction",
    "sort_order": 0
  }
];

export const fallbackCertifications = [
  {
    "id": 1,
    "name": "Software Engineer",
    "issuer": "HackerRank",
    "year": "14 Jul 2026",
    "detail": "Passed the HackerRank Software Engineer role certification test (ID 9E9A5564F2E7).",
    "image_url": "/images/cert-hackerrank.png",
    "image": "hackerrank",
    "image_key": "hackerrank",
    "sort_order": 0
  },
  {
    "id": 2,
    "name": "Introduction to JavaScript",
    "issuer": "Sololearn",
    "year": "20 Jul 2026",
    "detail": "Course certificate CC-C9GOLPIL — theoretical and practical understanding of JavaScript.",
    "image_url": "/images/cert-javascript.jpg",
    "image": "javascript",
    "image_key": "javascript",
    "sort_order": 1
  },
  {
    "id": 3,
    "name": "Introduction to Cloud Infrastructure: Describe cloud concepts",
    "issuer": "Microsoft",
    "year": "10 Jun 2026",
    "detail": "Azure cloud fundamentals — core cloud concepts and infrastructure services.",
    "image_url": "/images/cert-azure.png",
    "image": "azure",
    "image_key": "azure",
    "sort_order": 2
  }
];

export const fallbackPortfolio: PortfolioData = {
  profile: fallbackProfile as any,
  experiences: fallbackExperiences as any,
  projects: fallbackProjects as any,
  skill_groups: fallbackSkills as any,
  skills: fallbackSkills as any,
  educations: fallbackEducations as any,
  education: (fallbackEducations[0] || null) as any,
  certifications: fallbackCertifications as any,
};
